//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6
{
    public partial class DllTryIt
    {
        protected global::System.Web.UI.WebControls.TextBox txtZipInput;
        protected global::System.Web.UI.WebControls.Button btnValidateZip;
        protected global::System.Web.UI.WebControls.Label lblNormalizedZip;
        protected global::System.Web.UI.WebControls.Label lblValidationState;
        protected global::System.Web.UI.WebControls.Label lblValidationMessage;
    }
}
