//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.HiddenField hdnActiveTab;
        protected global::System.Web.UI.WebControls.TextBox txtMemberUsername;
        protected global::System.Web.UI.WebControls.TextBox txtMemberPassword;
        protected global::System.Web.UI.WebControls.Button btnMemberLogin;
        protected global::System.Web.UI.WebControls.Label lblMemberError;
        protected global::System.Web.UI.WebControls.TextBox txtStaffUsername;
        protected global::System.Web.UI.WebControls.TextBox txtStaffPassword;
        protected global::System.Web.UI.WebControls.Button btnStaffLogin;
        protected global::System.Web.UI.WebControls.Label lblStaffError;
    }
}
