//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6
{
    public partial class MemberRegister
    {
        protected global::System.Web.UI.WebControls.TextBox txtRegUsername;
        protected global::System.Web.UI.WebControls.TextBox txtRegPassword;
        protected global::System.Web.UI.WebControls.TextBox txtRegConfirm;
        protected global::System.Web.UI.UserControl ucCaptcha;
        protected global::System.Web.UI.WebControls.Button btnRegister;
        protected global::System.Web.UI.WebControls.Label lblRegError;
        protected global::System.Web.UI.WebControls.Label lblRegSuccess;
    }
}
