//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6
{
    public partial class Member
    {
        protected global::System.Web.UI.WebControls.Label lblWelcome;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.TextBox txtMemberZip;
        protected global::System.Web.UI.WebControls.Button btnGetForecast;
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentZip;
        protected global::System.Web.UI.WebControls.Label lblNormalized;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.BulletedList bltForecast;
        protected global::System.Web.UI.WebControls.Panel pnlSaveZip;
        protected global::System.Web.UI.WebControls.Button btnSaveZip;
        protected global::System.Web.UI.WebControls.Label lblSaveStatus;
        protected global::System.Web.UI.WebControls.GridView gvSavedZips;
        protected global::System.Web.UI.WebControls.TextBox txtOldPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Label lblChangeStatus;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
