//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6
{
    public partial class Staff
    {
        protected global::System.Web.UI.WebControls.Label lblStaffWelcome;
        protected global::System.Web.UI.WebControls.Button btnStaffLogout;
        protected global::System.Web.UI.WebControls.Label lblTotalVisits;
        protected global::System.Web.UI.WebControls.Label lblTotalMembers;
        protected global::System.Web.UI.WebControls.GridView gvMembers;
    }
}
