//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6
{
    public partial class WeatherTryIt
    {
        protected global::System.Web.UI.WebControls.TextBox txtWeatherZip;
        protected global::System.Web.UI.WebControls.Button btnGetForecast;
        protected global::System.Web.UI.WebControls.Label lblWeatherNormalizedZip;
        protected global::System.Web.UI.WebControls.Label lblWeatherStatus;
        protected global::System.Web.UI.WebControls.Label lblLastZipCookie;
        protected global::System.Web.UI.WebControls.BulletedList bltForecastResults;
    }
}
